[package]
name = "rust-via-api"
version = "0.1.0"
edition = "2021"

[lib]
name = "rust_via_api"
# "cdylib" is necessary to produce a shared library for Python to import from.
crate-type = ["cdylib"]

[dependencies]
hidapi = "*"
itertools = "0.12.1"
mockall = "0.12.1"

[dependencies.pyo3]
version = "0.20.0"
# "abi3-py38" tells pyo3 (and maturin) to build using the stable ABI with minimum Python version 3.8
features = ["abi3-py38"]
